# Generated by Django 2.1.3 on 2018-11-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Adres', max_length=50)),
                ('zip_code', models.CharField(help_text='Kod pocztowy', max_length=10)),
                ('city', models.CharField(help_text='Miasto', max_length=40)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nazwa drzewa', max_length=200)),
                ('size', models.PositiveSmallIntegerField(default=0)),
                ('photo_path', models.FilePathField(path='/home/familytreebuilder/', recursive=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Imiona', max_length=40)),
                ('last_name', models.CharField(help_text='Nazwisko', max_length=40)),
                ('birth_date', models.DateField(help_text='Datę narodzin')),
                ('death_date', models.DateField(help_text='Datę śmierci')),
                ('alive', models.BooleanField(help_text='Nieżyje?')),
                ('phone_number', models.CharField(help_text='Numer telefonu', max_length=15)),
                ('photo_path', models.FilePathField(path='/home/familytreebuilder/', recursive=True)),
                ('last_update', models.DateTimeField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.Member')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Login', max_length=40)),
                ('password', models.CharField(help_text='Hasło', max_length=40)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.User'),
        ),
        migrations.AddField(
            model_name='address',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.Member'),
        ),
    ]
