# Generated by Django 2.1.3 on 2018-11-27 14:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='Login')),
                ('email', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='Adres')),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Miasto')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nazwa drzewa')),
                ('size', models.PositiveSmallIntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Wybierz zdjęcie')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Imiona')),
                ('last_name', models.CharField(max_length=40, verbose_name='Nazwisko')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data narodzin')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Data śmierci')),
                ('alive', models.BooleanField(blank=True, null=True, verbose_name='Żyje?')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Numer telefonu')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Wybierz zdjęcie')),
                ('generation', models.SmallIntegerField(default=1)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.Address')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytreebuilder.Family')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='familytreebuilder.Member')),
                ('spouses', models.ManyToManyField(blank=True, related_name='_member_spouses_+', to='familytreebuilder.Member')),
            ],
        ),
    ]
