# Generated by Django 2.1.3 on 2018-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytreebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, help_text='Adres', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='Miasto', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, help_text='Kod pocztowy', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(blank=True, help_text='Nazwa drzewa', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Datę narodzin', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='death_date',
            field=models.DateField(blank=True, help_text='Datę śmierci', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(default=1, help_text='Nazwisko', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default=1, help_text='Imiona', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numer telefonu', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
