# Generated by Django 2.1.3 on 2018-11-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytreebuilder', '0003_auto_20181123_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/pictures/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/pictures/'),
        ),
    ]
