# Generated by Django 2.1.3 on 2018-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytreebuilder', '0004_auto_20181123_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='photo',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(null=True, upload_to='pictures/'),
        ),
    ]
